// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmpnoynctpjzweowzpiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtcG5veW5jdHBqendlb3d6cGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxNTcwNzgsImV4cCI6MjA0OTczMzA3OH0.P--sostbjU3IglkGhpv7STDtRhhzXVXeVdDdFhr7vJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);